name: tc-gateway

networks:
  tc-gateway:
    driver: bridge

services:

  registry:
    image: eclipsebasyx/aas-registry:1.5.1
    container_name: aas-registry
    ports:
        - "4000:4000"
    volumes:
      - ./src/basyx-conf/registry:/usr/share/config
    networks:
      - tc-gateway

  aas:
    image: eclipsebasyx/aas-server:1.5.1
    container_name: aas-server
    ports:
        - "4001:4001"
    volumes:
      - ./src/basyx-conf/server:/usr/share/config
      - ./src/basyx-source:/usr/share/config/aas
    networks:
      - tc-gateway

  gui: 
    image: eclipsebasyx/aas-gui:v2-240801
    container_name: aas-Gui
    ports:
      - "3000:3000"
    environment:
      - AAS_REGISTRY_PATH="http://registry:4000/registry/api/v1/registry"
      - AAS_REPO_PATH="http://aas:4001/aasServer/shells/"
    networks:
      - tc-gateway

  nginx:
    image: nginx
    container_name: aas-nginx
    volumes:
      - ./src/nginx-conf/aasServer.conf:/etc/nginx/conf.d/aasServer.conf
    ports:
      - "8090:80"
    environment:
      - NGINX_PORT=80
    networks:
      - tc-gateway
