version: "3.7"
name: tc-gateway

networks:
  tc-gateway:
    driver: bridge

services:

  registry:
    container_name: aas-registry
    image: eclipsebasyx/aas-registry:1.5.1
    ports:
        - "4000:4000"
    volumes:
      - ./src/basyx-conf/registry:/usr/share/config

  aas:
    image: eclipsebasyx/aas-server:1.5.1
    container_name: aas-server
    ports:
        - "4001:4001"
    volumes:
      - ./src/basyx-conf/server:/usr/share/config
      - ./src/basyx-source:/usr/share/config/aas


  gui: 
    image: eclipsebasyx/aas-gui:v230703
    container_name: aas-Gui
    ports:
        - "3000:3000"
    environment:
        -  VITE_REGISTRY_PATH="http://localhost:4000/registry"

  nginx:
    image: nginx
    volumes:
      - ./src/nginx-conf:/etc/nginx/templates
    ports:
      - "8090:80"
    environment:
      - NGINX_PORT=80
