name: tc-gateway

networks:
  tc-gateway:
    driver: bridge

services:
  aasx-server:
    container_name: aasx-server
    image: docker.io/adminshellio/aasx-server-blazor-for-demo:main
    ports:
      - "5001:5001"
    environment:
      - Kestrel__Endpoints__Http__Url=http://*:5001
    volumes:
      - ./src/aas-sources:/AasxServerBlazor/aasxs
    command: --no-security
    networks:
      - tc-gateway

  nginx:
    image: nginx
    container_name: aas-nginx
    volumes:
      - ./src/nginx-conf/aasServer.conf:/etc/nginx/conf.d/aasServer.conf
    ports:
      - "8090:80"
    environment:
      - NGINX_PORT=80
    networks:
      - tc-gateway
