version: "3.7"
name: tc-gateway

networks:
  tc-gateway:
    driver: bridge

services:
  basyx-aas-server:
    image: eclipsebasyx/aas-server:1.5.1
    container_name: basyx-aas-server
    ports:
      - "8091:4001"
    expose:
      - 8091
    volumes:
      - ./src/basyx-conf/server:/usr/share/config
      - ./src/basyx-source:/usr/share/config/aas

  basyx-aas-registry:
    image: eclipsebasyx/aas-registry:1.5.1
    container_name: basyx-aas-registry
    ports:
      - "8092:4000"
    expose:
      - 8092
    volumes:
      - ./src/basyx-conf/registry:/usr/share/config

  nginx:
    image: nginx
    volumes:
      - ./src/nginx-conf:/etc/nginx/templates
    ports:
      - "8090:80"
    environment:
      - NGINX_PORT=80